/*
 * Copyright (c) 2025 Focaltech Systems CO.,Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_FT9001_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_FT9001_CLOCKS_H_

#define FOCALTECH_CLOCK_CONFIG(reg, bit) \
	(((FOCALTECH_ ## reg ## _OFFSET) << 6U) | (bit))

/**
 * @name Register offsets
 * @{
 */
#define FOCALTECH_MULTICGTCR_OFFSET       0x3CU
#define FOCALTECH_SYSCGTCR_OFFSET         0x40U
#define FOCALTECH_AHB3CGTCR_OFFSET        0x44U
#define FOCALTECH_ARITHCGTCR_OFFSET       0x48U
#define FOCALTECH_IPSCGTCR_OFFSET         0x4CU
#define FOCALTECH_EPORTCGTR_OFFSET      0x84U

/** @} */

/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */

/* MULTICGTCR peripherals  clock_gatings */
#define FOCALTECH_CLOCK_OTPAHB     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 0U)
#define FOCALTECH_CLOCK_MCCM       FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 1U)
#define FOCALTECH_CLOCK_MCCADDR    FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 2U)
#define FOCALTECH_CLOCK_ADC        FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 3U)
#define FOCALTECH_CLOCK_MESH       FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 4U)
#define FOCALTECH_CLOCK_TC        FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 5U)
#define FOCALTECH_CLOCK_CLKOUT     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 6U)
#define FOCALTECH_CLOCK_KEYCTRL    FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 7U)
#define FOCALTECH_CLOCK_FOCALTECHRESET     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 8U)
#define FOCALTECH_CLOCK_OTPIPS     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 9U)
#define FOCALTECH_CLOCK_CPMIPS     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 10U)
#define FOCALTECH_CLOCK_TRACE     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 11U)
#define FOCALTECH_CLOCK_I2SM     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 12U)
#define FOCALTECH_CLOCK_I2SS     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 13U)
#define FOCALTECH_CLOCK_CRC0     FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 14U)
#define FOCALTECH_CLOCK_CRC1      FOCALTECH_CLOCK_CONFIG(MULTICGTCR, 15U)

/* SYSCGTCR peripherals */
#define FOCALTECH_CLOCK_SSISLV0      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 0U)
#define FOCALTECH_CLOCK_DMAC0      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 1U)
#define FOCALTECH_CLOCK_DMAC1       FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 2U)
#define FOCALTECH_CLOCK_AHB2MUX       FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 3U)
#define FOCALTECH_CLOCK_PXLP1AHB    FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 10U)
#define FOCALTECH_CLOCK_PXLP2AHB    FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 11U)
#define FOCALTECH_CLOCK_SRAMD      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 12U)
#define FOCALTECH_CLOCK_SRAM0      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 13U)
#define FOCALTECH_CLOCK_SRAM1      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 14U)
#define FOCALTECH_CLOCK_SRAM2      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 15U)
#define FOCALTECH_CLOCK_SRAM34      FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 16U)
#define FOCALTECH_CLOCK_SSI3       FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 17U)
#define FOCALTECH_CLOCK_SSI4       FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 18U)
#define FOCALTECH_CLOCK_SSI5        FOCALTECH_CLOCK_CONFIG(SYSCGTCR, 19U)


/* AHB3CGTCR peripherals */
#define FOCALTECH_CLOCK_ROM       FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 0U)
#define FOCALTECH_CLOCK_ROMOTPMUX    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 1U)
#define FOCALTECH_CLOCK_AHB3MUX    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 2U)
#define FOCALTECH_CLOCK_USBC    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 3U)
#define FOCALTECH_CLOCK_PXLP1APB    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 4U)
#define FOCALTECH_CLOCK_PXLP2APB    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 5U)
#define FOCALTECH_CLOCK_I2S0    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 6U)
#define FOCALTECH_CLOCK_I2S1    FOCALTECH_CLOCK_CONFIG(AHB3CGTCR, 7U)

/* ARITHCGTCR peripherals */
#define FOCALTECH_CLOCK_AES        FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 1U)
#define FOCALTECH_CLOCK_SM4        FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 2U)
#define FOCALTECH_CLOCK_RFAESSM4   FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 4U)
#define FOCALTECH_CLOCK_CRYPTO     FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 5U)
#define FOCALTECH_CLOCK_SHA        FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 6U)
#define FOCALTECH_CLOCK_EDMAC0     FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 7U)
#define FOCALTECH_CLOCK_DES        FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 8U)
#define FOCALTECH_CLOCK_ZUC        FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 9U)
#define FOCALTECH_CLOCK_AHB2MLB    FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 10U)
#define FOCALTECH_CLOCK_AHB2IPS2   FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 11U)
#define FOCALTECH_CLOCK_TRNG   FOCALTECH_CLOCK_CONFIG(ARITHCGTCR, 12U)


/* IPSCGTCR peripherals */
#define FOCALTECH_CLOCK_PINCTRL    FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 0U)
#define FOCALTECH_CLOCK_WDT      FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 1U)
#define FOCALTECH_CLOCK_TC      FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 2U)
#define FOCALTECH_CLOCK_PIT0       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 3U)
#define FOCALTECH_CLOCK_PIT1       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 4U)
#define FOCALTECH_CLOCK_USI0       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 5U)
#define FOCALTECH_CLOCK_EDMAC1     FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 6U)
#define FOCALTECH_CLOCK_SPI0       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 7U)
#define FOCALTECH_CLOCK_SPI1       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 8U)
#define FOCALTECH_CLOCK_SPI2       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 9U)
#define FOCALTECH_CLOCK_UART0      FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 10U)
#define FOCALTECH_CLOCK_UART1      FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 11U)
#define FOCALTECH_CLOCK_USI1       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 12U)
#define FOCALTECH_CLOCK_CAN0       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 13U)
#define FOCALTECH_CLOCK_I2C0       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 14U)
#define FOCALTECH_CLOCK_PWM0       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 15U)
#define FOCALTECH_CLOCK_I2C1       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 16U)
#define FOCALTECH_CLOCK_CAN1       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 17U)
#define FOCALTECH_CLOCK_UART2      FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 18U)
#define FOCALTECH_CLOCK_QADC       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 20U)
#define FOCALTECH_CLOCK_DAC        FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 21U)
#define FOCALTECH_CLOCK_MCCI        FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 22U)
#define FOCALTECH_CLOCK_PWMT0        FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 23U)
#define FOCALTECH_CLOCK_LD         FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 24U)
#define FOCALTECH_CLOCK_PWMT1       FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 25U)
#define FOCALTECH_CLOCK_PGD        FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 26U)
#define FOCALTECH_CLOCK_SECDET     FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 27U)
#define FOCALTECH_CLOCK_PCI        FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 28U)
#define FOCALTECH_CLOCK_RTC     FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 29U)
#define FOCALTECH_CLOCK_AHB2IPS    FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 30U)
#define FOCALTECH_CLOCK_PWMT2   FOCALTECH_CLOCK_CONFIG(IPSCGTCR, 31U)

/* EPORTCGTR peripherals */
#define FOCALTECH_CLOCK_EPORT0    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 0U)
#define FOCALTECH_CLOCK_EPORT1    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 1U)
#define FOCALTECH_CLOCK_EPORT2    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 2U)
#define FOCALTECH_CLOCK_EPORT3    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 3U)
#define FOCALTECH_CLOCK_EPORT4    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 4U)
#define FOCALTECH_CLOCK_EPORT5    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 5U)
#define FOCALTECH_CLOCK_EPORT6    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 6U)
#define FOCALTECH_CLOCK_EPORT7    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 7U)
#define FOCALTECH_CLOCK_ACMP0    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 8U)
#define FOCALTECH_CLOCK_ACMP1    FOCALTECH_CLOCK_CONFIG(EPORTCGTR, 9U)

/** @} */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_FT90_CLOCKS_H_ */
