/*
 * Copyright (c) 2022 Focaltech Systems CO.,Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

 #ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RESET_FT9001_H_
 #define ZEPHYR_INCLUDE_DT_BINDINGS_RESET_FT9001_H_
 
 /**
  * Encode RCU register offset and configuration bit.
  *
  * - 0..5: bit number
  * - 6..14: offset
  * - 15: reserved
  *
  * @param reg RCU register name (expands to GD32_{reg}_OFFSET)
  * @param bit Configuration bit
  */
 #define FOCALTECH_RESET_CONFIG(reg, bit) \
	 (((FOCALTECH_ ## reg ## _OFFSET) << 6U) | (bit))
	 
 /**
  * @name Register offsets
  * @{
  */
 #define FOCALTECH_MULTIRSTCR_OFFSET       0xACU
 #define FOCALTECH_SYSRSTCR_OFFSET         0xB0U
 #define FOCALTECH_AHB3RSTCR_OFFSET        0xB4U
 #define FOCALTECH_ARITHRSTCR_OFFSET       0xB8U
 #define FOCALTECH_IPSRSTCR_OFFSET         0xBCU
 #define FOCALTECH_EPORTRSTR_OFFSET        0x88U
 
 /** @} */
 
 /**
  * @name Clock enable/disable definitions for peripherals
  * @{
  */
 
 /* MULTIRSTCR peripherals */
 /* MULTICGTCR peripherals  clock_gatings */
 #define FOCALTECH_RESET_OTPAHB     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 0U)
 #define FOCALTECH_RESET_MCC       FOCALTECH_RESET_CONFIG(MULTICRSCR, 1U)
 #define FOCALTECH_RESET_MCCADDR    FOCALTECH_RESET_CONFIG(MULTIRSTCR, 2U)
 #define FOCALTECH_RESET_MESH       FOCALTECH_RESET_CONFIG(MULTIRSTCR, 4U)
 #define FOCALTECH_RESET_TC        FOCALTECH_RESET_CONFIG(MULTIRSTCR, 5U)
 #define FOCALTECH_RESET_CLKOUT     FOCALTECH_RESET_CONFIG(MULTRSGTCR, 6U)
 #define FOCALTECH_RESET_KEYCTRL    FOCALTECH_RESET_CONFIG(MULTIRSTCR, 7U)
 #define FOCALTECH_RESET_FOCALTECHRESET     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 8U)
 #define FOCALTECH_RESET_OTPIPS     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 9U)
 #define FOCALTECH_RESET_CPMIPS     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 10U)
 #define FOCALTECH_RESET_TRACE     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 11U)
 #define FOCALTECH_RESET_I2SM     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 12U)
 #define FOCALTECH_RESET_I2SS     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 13U)
 #define FOCALTECH_RESET_CRC0     FOCALTECH_RESET_CONFIG(MULTIRSTCR, 14U)
 #define FOCALTECH_RESET_CRC1      FOCALTECH_RESET_CONFIG(MULTIRSTCR, 15U)
 
 
 /* SYSRSTCR peripherals */
 #define FOCALTECH_RESET_SSISLV0      FOCALTECH_RESET_CONFIG(SYSRSTCR, 0U)
 #define FOCALTECH_RESET_DMAC0      FOCALTECH_RESET_CONFIG(SYSRSTCR, 1U)
 #define FOCALTECH_RESET_DMAC1       FOCALTECH_RESET_CONFIG(SYSRSTCR, 2U)
 #define FOCALTECH_RESET_AHB2MUX       FOCALTECH_RESET_CONFIG(SYSRSTCR, 3U)
 #define FOCALTECH_RESET_PXLP1AHB    FOCALTECH_RESET_CONFIG(SYSRSTCR, 10U)
 #define FOCALTECH_RESET_PXLP2AHB    FOCALTECH_RESET_CONFIG(SYSRSTCR, 11U)
 #define FOCALTECH_RESET_SRAMD      FOCALTECH_RESET_CONFIG(SYSRSTCR, 12U)
 #define FOCALTECH_RESET_SRAM0      FOCALTECH_RESET_CONFIG(SYSRSTCR, 13U)
 #define FOCALTECH_RESET_SRAM1      FOCALTECH_RESET_CONFIG(SYSRSTCR, 14U)
 #define FOCALTECH_RESET_SRAM2      FOCALTECH_RESET_CONFIG(SYSRSTCR, 15U)
 #define FOCALTECH_RESET_SRAM34      FOCALTECH_RESET_CONFIG(SYSRSTCR, 16U)
 #define FOCALTECH_RESET_SSI3       FOCALTECH_RESET_CONFIG(SYSRSTCR, 17U)
 #define FOCALTECH_RESET_SSI4       FOCALTECH_RESET_CONFIG(SYSRSTCR, 18U)
 #define FOCALTECH_RESET_SSI5        FOCALTECH_RESET_CONFIG(SYSRSTCR, 19U)
 
 
 
 /* AHB3RSTCR peripherals */
 #define FOCALTECH_RESET_ROM       FOCALTECH_RESET_CONFIG(AHB3RSTCR, 0U)
 #define FOCALTECH_RESET_ROMOTPMUX    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 1U)
 #define FOCALTECH_RESET_AHB3MUX    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 2U)
 #define FOCALTECH_RESET_USBC    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 3U)
 #define FOCALTECH_RESET_PXLP1APB    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 4U)
 #define FOCALTECH_RESET_PXLP2APB    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 5U)
 #define FOCALTECH_RESET_I2S0    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 6U)
 #define FOCALTECH_RESET_I2S1    FOCALTECH_RESET_CONFIG(AHB3RSTCR, 7U)
 
 /* ARITHRSTCR peripherals */
 #define FOCALTECH_RESET_AES        FOCALTECH_RESET_CONFIG(ARITHRSTCR, 1U)
 #define FOCALTECH_RESET_SM4        FOCALTECH_RESET_CONFIG(ARITHRSTCR, 2U)
 #define FOCALTECH_RESET_RFAESSM4   FOCALTECH_RESET_CONFIG(ARITHRSTCR, 4U)
 #define FOCALTECH_RESET_CRYPTO     FOCALTECH_RESET_CONFIG(ARITHRSTCR, 5U)
 #define FOCALTECH_RESET_SHA        FOCALTECH_RESET_CONFIG(ARITHRSTCR, 6U)
 #define FOCALTECH_RESET_EDMAC0     FOCALTECH_RESET_CONFIG(ARITHRSTCR, 7U)
 #define FOCALTECH_RESET_DES        FOCALTECH_RESET_CONFIG(ARITHRSTCR, 8U)
 #define FOCALTECH_RESET_ZUC        FOCALTECH_RESET_CONFIG(ARITHRSTCR, 9U)
 #define FOCALTECH_RESET_AHB2MLB    FOCALTECH_RESET_CONFIG(ARITHRSTCR, 10U)
 #define FOCALTECH_RESET_AHB2IPS2   FOCALTECH_RESET_CONFIG(ARITHRSTCR, 11U)
 #define FOCALTECH_RESET_TRNG   FOCALTECH_RESET_CONFIG(ARITHRSTCR, 12U)
 
 
 /* IPSRSTCR peripherals */
 #define FOCALTECH_RESET_PINCTRL    FOCALTECH_RESET_CONFIG(IPSRSTCR, 0U)
 #define FOCALTECH_RESET_WDT      FOCALTECH_RESET_CONFIG(IPSRSTCR, 1U)
 
 #define FOCALTECH_RESET_PIT0       FOCALTECH_RESET_CONFIG(IPSRSTCR, 3U)
 #define FOCALTECH_RESET_PIT1       FOCALTECH_RESET_CONFIG(IPSRSTCR, 4U)
 #define FOCALTECH_RESET_USI0       FOCALTECH_RESET_CONFIG(IPSRSTCR, 5U)
 #define FOCALTECH_RESET_EDMAC1     FOCALTECH_RESET_CONFIG(IPSRSTCR, 6U)
 #define FOCALTECH_RESET_SPI0       FOCALTECH_RESET_CONFIG(IPSRSTCR, 7U)
 #define FOCALTECH_RESET_SPI1       FOCALTECH_RESET_CONFIG(IPSRSTCR, 8U)
 #define FOCALTECH_RESET_SPI2       FOCALTECH_RESET_CONFIG(IPSRSTCR, 9U)
 #define FOCALTECH_RESET_UART0      FOCALTECH_RESET_CONFIG(IPSRSTCR, 10U)
 #define FOCALTECH_RESET_UART1      FOCALTECH_RESET_CONFIG(IPSRSTCR, 11U)
 #define FOCALTECH_RESET_USI1       FOCALTECH_RESET_CONFIG(IPSRSTCR, 12U)
 #define FOCALTECH_RESET_CAN0       FOCALTECH_RESET_CONFIG(IPSRSTCR, 13U)
 #define FOCALTECH_RESET_I2C0       FOCALTECH_RESET_CONFIG(IPSRSTCR, 14U)
 #define FOCALTECH_RESET_PWM0       FOCALTECH_RESET_CONFIG(IPSRSTCR, 15U)
 #define FOCALTECH_RESET_I2C1       FOCALTECH_RESET_CONFIG(IPSRSTCR, 16U)
 #define FOCALTECH_RESET_CAN1       FOCALTECH_RESET_CONFIG(IPSRSTCR, 17U)
 #define FOCALTECH_RESET_UART2      FOCALTECH_RESET_CONFIG(IPSRSTCR, 18U)
 #define FOCALTECH_RESET_QADC       FOCALTECH_RESET_CONFIG(IPSRSTCR, 20U)
 #define FOCALTECH_RESET_DAC        FOCALTECH_RESET_CONFIG(IPSRSTCR, 21U)
 #define FOCALTECH_RESET_MCC        FOCALTECH_RESET_CONFIG(IPSRSTCR, 22U)
 #define FOCALTECH_RESET_PWMT0        FOCALTECH_RESET_CONFIG(IPSRSTCR, 23U)
 #define FOCALTECH_RESET_LD         FOCALTECH_RESET_CONFIG(IPSRSTCR, 24U)
 #define FOCALTECH_RESET_PWMT1       FOCALTECH_RESET_CONFIG(IPSRSTCR, 25U)
 #define FOCALTECH_RESET_PGD        FOCALTECH_RESET_CONFIG(IPSRSTCR, 26U)
 #define FOCALTECH_RESET_SECDET     FOCALTECH_RESET_CONFIG(IPSRSTCR, 27U)
 #define FOCALTECH_RESET_PCI        FOCALTECH_RESET_CONFIG(IPSRSTCR, 28U)
 #define FOCALTECH_RESET_PMURTC     FOCALTECH_RESET_CONFIG(IPSRSTCR, 29U)
 #define FOCALTECH_RESET_AHB2IPS    FOCALTECH_RESET_CONFIG(IPSRSTCR, 30U)
 #define FOCALTECH_RESET_PWMT2   FOCALTECH_RESET_CONFIG(IPSRSTCR, 31U)
 
 /* EPORTRSTR peripherals */
 #define FOCALTECH_RESET_EPORT0    FOCALTECH_RESET_CONFIG(EPORTRSTR, 0U)
 #define FOCALTECH_RESET_EPORT1    FOCALTECH_RESET_CONFIG(EPORTRSTR, 1U)
 #define FOCALTECH_RESET_EPORT2    FOCALTECH_RESET_CONFIG(EPORTRSTR, 2U)
 #define FOCALTECH_RESET_EPORT3    FOCALTECH_RESET_CONFIG(EPORTRSTR, 3U)
 #define FOCALTECH_RESET_EPORT4    FOCALTECH_RESET_CONFIG(EPORTRSTR, 4U)
 #define FOCALTECH_RESET_EPORT5    FOCALTECH_RESET_CONFIG(EPORTRSTR, 5U)
 #define FOCALTECH_RESET_EPORT6    FOCALTECH_RESET_CONFIG(EPORTRSTR, 6U)
 #define FOCALTECH_RESET_EPORT7    FOCALTECH_RESET_CONFIG(EPORTRSTR, 7U)
 #define FOCALTECH_RESET_ACMP0    FOCALTECH_RESET_CONFIG(EPORTRSTR, 8U)
 #define FOCALTECH_RESET_ACMP1    FOCALTECH_RESET_CONFIG(EPORTRSTR, 9U)
 
 
 /** @} */
 
 #endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RESET_FT9001_H_ */
 